### ISSUE TITLE
Howto

### ISSUE THREAD

**Issue by alex792** [razerofficial/ChromaEmulator#1]
Hello!

Could you please let know how to use this emulator? After download and installation I run it, set a check on the keyboard checkbox and pressed show. Now I see the virtual keyboard, but Synapse does not detect it and also Razer sample application does not detect it. Please advise.

**Comment by Comango104** [comment]
I couldn't get it working either...

**Comment by robtrevino** [comment]
same issue

**Comment by GuzioMG** [comment]
Yep, my Synapse and RESTapi also don't detect.....

EDIT: RESTapi seems to magically start working and a weird entry appeared in Razer Synapse -> Chroma Connect -> Apps (Yes, apps - not devices. No idea why.). Anyway, it still can't be recognized by Synapse as an actual device.

**Comment by andrewputrajaya** [comment]
ChromaEmulator works for showing effect from ChromaSDK integrated Apps & Games only, not from Synapse. For the supported games refer to this link: https://www2.razer.com/chroma-workshop-games
