### ISSUE TITLE
Keypad displays Chroma linked device effects

### ISSUE THREAD

**Issue by ccbrown** [razerofficial/ChromaEmulator#2]
Not sure if this is a bug in the emulator, a bug in the SDK, or just a subtle SDK feature that I can't find documentation for, but whenever I trigger a Chroma linked device effect, it appears on the virtual keypad. So if you trigger effects for Chroma linked devices and keypads at the same time, they conflict with each other, producing bad results.

In particular, the loading animation for chroma linked devices causes the keypad to fill vertically. But the loading animation for keypads causes them to fill horizontally. As far as I can tell, it's not possible to display loading animations for chroma linked devices and keypads simultaneously unless you use `CreateEffect` to target individual devices (It just produces chaotic flickering.).

This can be reproduced using the Razer Chroma SDK C++ sample application and happens regardless of the `device_supported` element in ChromaAppInfo.xml (This behavior would make sense if `keypad` were set to "0", but it's not in my case.).

**Comment by andrewputrajaya** [comment]
This is expected behavior that also applies on the actual Keypad device
