### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by SinanAkkoyun** [razerofficial/ChromaEmulator#3]
Please publish the source code.

**Comment by OpaqueReptile** [comment]
The installer claims that this is GPLv3... but there's no source?

**Comment by tgraupmann** [comment]
The eula.txt was in reference to the InnoSetup installer script only.
https://github.com/razerofficial/ChromaEmulator/blob/master/installer.iss

I've switched the eula.txt to the MIT license.
https://github.com/razerofficial/ChromaEmulator/blob/master/eula.txt
