### ISSUE TITLE
Proper responses for QueryDevice?

### ISSUE THREAD

**Issue by d8ahazard** [razerofficial/ChromaEmulator#4]
Hi there!

I'm using Colore in conjunction with the Chroma SDK to create an app that will, ideally, be able to enumerate connected Razer devices, and then control them with various sets of color data my app produces.

However, I don't actually own any Razer devices at the moment, so I'm trying to do all this with the emulator. However, I use the QueryDevice function to determine if a device is attached, and it doesn't appear as if the emulator works with the QueryDevice function.

I'm just curious, are there specific GUIDs for the chroma emulator devices I can use to work directly with them, or should I just write some kind of "use emulator" override in my system that instead just presents devices when enabled?

Any advice would be appreciated, TIA!

**Comment by andrewputrajaya** [comment]
ChromaSDK QueryDevice function is mainly being used to retrieve the presence of physical device connected to the system, emulator is virtual device so it's unrelated. 

There is no specific GUID for chroma emulator devices, the purpose of emulator here is only for development, basically to give an illustration on how the chroma effect from chromaSDK appears in the device.
