### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Erikcb91** [razerofficial/ChromaEmulator#5]
Hi, i'm trying to use the emulator but it's not working, after some research i noticed there is no SDK services at all, i have no idea if i can reinstall it or whatever.

I read that reinstalling synapse would install SDK too, but for some reason it doesn't for me, i tried it several times, and i also tried removing every razer file/register entry/whatever from my computer and doing a clean reinstallation, but it's still the same.

i also can't find a way to download the Chroma SDK Core components as an install file or anything like that, i checked in "https://developer.razer.com/works-with-chroma/download/" but i can't find the link there, is there any way of installing SDK on its own? Cause Synapse is not installing it for me.

Thanks in advance :)

**Comment by andrewputrajaya** [comment]
Hi, you can actually uninstalling ChromaSDK without uninstalling Synapse by removing the Chroma Connect module in Synapse, 
![image](https://user-images.githubusercontent.com/1481207/228992127-bfb64290-3b92-41aa-bfd8-c86c2bbc6069.png)

and then you can re-install by selecting the 'Install & Restart' button
![image](https://user-images.githubusercontent.com/1481207/228992368-17fde311-a6bb-4e6f-bfee-41ce9cd5608c.png)

please ensure the following folders and files are removed after uninstallation:
C:\Program Files (x86)\Razer Chroma SDK
C:\Program Files\Razer Chroma SDK
C:\Windows\SysWOW64\RzChromaSDK.dll
C:\Windows\System32\RzChromaSDK64.dll
(in case it's not automatically deleted after uninstallation, pls delete manually)

if problem persists, you may gather some logs for checking:
https://mysupport.razer.com/app/answers/detail/a_id/1462/~/how-to-gather-razer-synapse-3-logs-from-a-pc

**Comment by Erikcb91** [comment]
It's still the same, the problem is that the services arent even there, all the SDK files are installed properly when i install Chroma Connect, but the services are not there.

**Comment by andrewputrajaya** [comment]
Please try the following steps:
1. Open a Command Prompt window as an Administrator.
2. Type the following command: **cd C:\Program Files (x86)\Razer Chroma SDK\bin**
3. Next, type the following command: **sc.exe create "Razer Chroma SDK Service" binPath= "C:\Program Files (x86)\Razer Chroma SDK\bin\RzSDKService.exe" start= auto**
4. If the service is successfully created, you should see a message saying "[SC] CreateService SUCCESS".
5. Restart system

**Comment by Erikcb91** [comment]
> Please try the following steps:
> 
> 1. Open a Command Prompt window as an Administrator.
> 2. Type the following command: **cd C:\Program Files (x86)\Razer Chroma SDK\bin**
> 3. Next, type the following command: **sc.exe create "Razer Chroma SDK Service" binPath= "C:\Program Files (x86)\Razer Chroma SDK\bin\RzSDKService.exe" start= auto**
> 4. If the service is successfully created, you should see a message saying "[SC] CreateService SUCCESS".
> 5. Restart system

Already tried that but for some reason it's not working, the service is created, but i can't run it at all.

![image](https://user-images.githubusercontent.com/75399666/229561494-569b3329-aaf3-4bdb-8155-d7c981e63c73.png)

And the Conect module is still the same.

**Comment by Erikcb91** [comment]
Nevermind, apparently i managed to make it work, the service wasn't starting because the route was missinf the "", i edited the location in the registry and it seems to be working now (i still don't understand why Synapse ain't installing the services properly on its own, but whatever)

Thanks for your help!
